image: alpine:latest

stages:
  - build
  - deploy

variables:
  JAR_FILE: test_project_codedeploy-0.0.1-SNAPSHOT.jar
  AWS_DEFAULT_REGION: ap-northeast-2
  S3_BUCKET: bigmtn1113-s3-cd-revisions
  S3_BUCKET_DIR: java-test
  CODEDEPLOY_APPLICATION: bigmtn1113-cd-application
  CODEDEPLOY_GROUP: bigmtn1113-cd-group

gradle-build-job:
  image: amazoncorretto:8
  stage: build
  tags:
    - SharedRunner
  before_script:
    - java -version
  script:
    - chmod +x ./gradlew
    - ./gradlew build
    - mv ./build/libs/$JAR_FILE ./
  cache:
    key: "JAR file"
    policy: push
    paths:
      - ./$JAR_FILE

codedeploy-job:
  stage: deploy
  tags:
    - SharedRunner
  before_script:
    - echo "Install zip"
    - apk add zip
    - zip -h

    - echo "Install aws cli"
    - apk add --no-cache python3 py3-pip
    - pip3 install awscli
    - rm -rf /var/cache/apk/*
    - aws --version
  script:
    - zip -r $S3_BUCKET_DIR-$CI_COMMIT_SHORT_SHA.zip ./$JAR_FILE ./script/ ./appspec.yml

    - aws s3 cp $S3_BUCKET_DIR-$CI_COMMIT_SHORT_SHA.zip s3://$S3_BUCKET/$S3_BUCKET_DIR/
    - aws deploy create-deployment --application-name $CODEDEPLOY_APPLICATION --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $CODEDEPLOY_GROUP --s3-location bucket=$S3_BUCKET,bundleType=zip,key=$S3_BUCKET_DIR/$S3_BUCKET_DIR-$CI_COMMIT_SHORT_SHA.zip
  cache:
    key: "JAR file"
    policy: pull
    paths:
      - ./$JAR_FILE
