version: 0.0
os: linux

files:
  - source: /test_project_codedeploy-0.0.1-SNAPSHOT.jar
    destination: /spring-boot-helloworld/release

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: script/ApplicationStop.sh
      timeout: 20
      runas: ec2-user
  BeforeInstall:
    - location: script/BeforInstall.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: script/AfterInstall.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: script/ApplicationStart.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: script/ValidateService.sh
      timeout: 60
      runas: ec2-user
